apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: convention-workload-probes
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/language: golang
  name: convention-workload-probes
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      CONVENTION_PREFIX_PLACEHOLDER/readinessProbe: '{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":5,"periodSeconds":5}'
  source:
    git:
      ref:
        branch: main
      url: https://github.com/carto-run/app-golang-kpack