apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: PACKAGE_NAME_PLACEHOLDER.0.0.0
spec:
  refName: PACKAGE_NAME_PLACEHOLDER
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: PACKAGE_NAME_PLACEHOLDER
spec:
  displayName: multi-purpose-convention-server
  longDescription: PACKAGE_LONG_DESCRIPTION_PLACEHOLDER
  maintainers:
  - name: PACKAGE_MAINTAINERS_PLACEHOLDER
  providerName: PACKAGE_MAINTAINERS_PLACEHOLDER
  shortDescription: PACKAGE_SHORT_DESCRIPTION_PLACEHOLDER
  supportDescription: PACKAGE_MAINTAINERS_PLACEHOLDER

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: multi-purpose-convention-server
spec:
  packageRef:
    refName: PACKAGE_NAME_PLACEHOLDER
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: multi-purpose-convention-server-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
