---
apiVersion: v1
kind: Namespace
metadata:
  name: ARTIFACT_ID_PLACEHOLDER

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ARTIFACT_ID_PLACEHOLDER-selfsigned-issuer
  namespace: ARTIFACT_ID_PLACEHOLDER
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ARTIFACT_ID_PLACEHOLDER-webhook-cert
  namespace: ARTIFACT_ID_PLACEHOLDER
spec:
  subject:
    organizations:
    - vmware
    organizationalUnits:
    - tanzu
  commonName: ARTIFACT_ID_PLACEHOLDER-webhook.ARTIFACT_ID_PLACEHOLDER.svc
  dnsNames:
  - ARTIFACT_ID_PLACEHOLDER-webhook.ARTIFACT_ID_PLACEHOLDER.svc
  - ARTIFACT_ID_PLACEHOLDER-webhook.ARTIFACT_ID_PLACEHOLDER.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ARTIFACT_ID_PLACEHOLDER-selfsigned-issuer
  secretName: ARTIFACT_ID_PLACEHOLDER-webhook-cert
  revisionHistoryLimit: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ARTIFACT_ID_PLACEHOLDER-webhook
  namespace: ARTIFACT_ID_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ARTIFACT_ID_PLACEHOLDER-webhook
  template:
    metadata:
      labels:
        app: ARTIFACT_ID_PLACEHOLDER-webhook
    spec:
      containers:
      - name: webhook
        image: ARTIFACT_ID_PLACEHOLDER@sha
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8443"
        - name: ANNOTATION_PREFIX
          value: "example.com"
        ports:
        - containerPort: 8443
          name: webhook
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: webhook
            path: /healthz
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: webhook
            path: /healthz
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - name: certs
          mountPath: /config/certs
          readOnly: true
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            secretName: ARTIFACT_ID_PLACEHOLDER-webhook-cert
---
apiVersion: v1
kind: Service
metadata:
  name: ARTIFACT_ID_PLACEHOLDER-webhook
  namespace: ARTIFACT_ID_PLACEHOLDER
spec:
  selector:
    app: ARTIFACT_ID_PLACEHOLDER-webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: webhook
---
apiVersion: conventions.carto.run/v1alpha1
kind: ClusterPodConvention
metadata:
  name: ARTIFACT_ID_PLACEHOLDER
spec:
  webhook:
    certificate:
      namespace: ARTIFACT_ID_PLACEHOLDER
      name: ARTIFACT_ID_PLACEHOLDER-webhook-cert
    clientConfig:
      service:
        name: ARTIFACT_ID_PLACEHOLDER-webhook
        namespace: ARTIFACT_ID_PLACEHOLDER
