---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-group: "ARTIFACT_ID_PLACEHOLDER"
    kapp.k14s.io/change-rule.create-order-0: "upsert after upserting ARTIFACT_ID_PLACEHOLDER-repository"
    packaging.carvel.dev/downgradable: ""
  name: ARTIFACT_ID_PLACEHOLDER
  namespace: tap-install
spec:
  packageRef:
    refName: PACKAGE_NAME_PLACEHOLDER
    versionSelection:
      constraints: ">0.0.0"
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
    - secretRef:
        name: ARTIFACT_ID_PLACEHOLDER-install-values
